#!/bin/sh

# Check for correct number of arguments
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <data_size> <num_storage_servers> <num_worker_nodes>"
    exit 1
fi

# Assign arguments to variables
data_size=$1
num_storage_servers=$2
num_worker_nodes=$3
base_port=50050

# Generate data
./cmake/build/generateData "$data_size" &
datagen_pid=$!

# Function to start a server
start_server() {
    server_type=$1 # Either StorageNode or WorkerNode
    start_port=$2
    num_servers=$3

    for (( i=0; i<num_servers; i++ )); do
        port=$((start_port + i))
        ./cmake/build/"$server_type" 127.0.0.1 "$port" &
        server_ports+=("$port")
    done
}

# Start Storage Nodes
start_server "StorageNode" $base_port $num_storage_servers

# Calculate base port for Worker Nodes to avoid port conflicts
worker_base_port=$((base_port + num_storage_servers))

# Start Worker Nodes
start_server "WorkerNode" $worker_base_port $num_worker_nodes

# Wait for datagen to complete
wait $datagen_pid
sleep 3

# Execute main
main_command=./cmake/build/"main 127.0.0.1 50049"
for port in "${server_ports[@]}"; do
    main_command+=" 127.0.0.1 $port"
done

eval "$main_command"



